config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'book/return', to: "book#return"
  get 'book/borrow', to: "book#borrow"
  resources :book
  root 'homepage#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  just_define_datetime_picker :date_borrowed
  #validates :date_borrowed, :presence => true
  acts_as_paranoid
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
  acts_as_paranoid
  def full_name
    "#{email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate

  private

  def authenticate
    authenticate_user! unless params[:controller] =~ /^admin\//
  end

  def set_admin_locale
    I18n.locale = :hr
  end


end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def index
    @books = Book.all
    #TODO USER_ID
    @borrowed_books = Book.where(user_id: 1)
  end

  def show
    @book = Book.find(params[:id])

  end

  def borrow
    @book = Book.where(id: params[:book_id]).update_all(user_id: params[:user_id], date_borrowed: DateTime.now)
    redirect_to :action => "index"
  end

  def return
    @book = Book.where(id: params[:book_id]).update_all(user_id: nil, date_borrowed: nil)
    redirect_to action: "index"
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  skip_before_action :authenticate
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/book/index.html.erb
<h3>POSUĐENO:</h3>
<ul>
  <% @borrowed_books.each do |book| %>
  <li>
  <pre><%= link_to "#{book.title} - #{book.author}", book_path(book.id)%>
    POSUĐENO: <%= book.date_borrowed %>
    <%= link_to "VRATI", :controller => :book, :action => :return, :user_id => current_user.id, :book_id => book.id %>
  </pre>
  </li>
  <% end %>
</ul>
<h3>KNJIGE:</h3>
<% @books.each do |book| %>
<p><%= link_to "#{book.title} - #{book.author}", book_path(book.id)%></p>
<% end %>

<%= link_to "Logout", destroy_user_session_path, method: :delete %>

app/views/book/show.html.haml
.content
%h1= @book.title
%p
  Autor: #{@book.author}
  %br
  Opis: #{@book.description}
  %br
  Mjesto: #{@book.place}
  %br
  Izdavač: #{@book.publisher}
  %br
  Godina: #{@book.year}
  %br
  Signatura: #{@book.signature}
.links
= link_to "Posudi", :controller => :book, :action => :borrow, :user_id => current_user.id, :book_id => @book.id
%br
= link_to "Natrag", book_index_url

app/views/homepage/index.html.erb
<div style="padding: 30px 80px; font-size: 2em; height: 500px;">
<h1>INFOSHOP PIPPILOTTA</h1>
<p><%= link_to "Administracijsko sučelje", new_admin_user_session_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Infoshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>